os: linux
dist: xenial

language: java

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - PATH=/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH

script:
  - gradle build